version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: apiportal-front
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - VITE_APP_STRAPI_URL=${VITE_APP_STRAPI_URL}
      - VITE_PORT=${FRONTEND_PORT}
    depends_on:
      - backend
    networks:
      - apimarket-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: apiportal-cms
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      HOST: 0.0.0.0
      PORT: ${BACKEND_PORT}
      APP_KEYS: ${APP_KEYS}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT} # Internal PostgreSQL port
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: 'false'
      #AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      #AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      #AWS_REGION: ${AWS_REGION:-}
      #AWS_BUCKET: ${AWS_BUCKET:-}
      #AWS_BUCKET_SUBDIRECTORY: ${AWS_BUCKET_SUBDIRECTORY:-}
      #AWS_CDN_DOMAIN: ${AWS_CDN_DOMAIN:-}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - apimarket-net

  database:
    image: postgres:13-alpine
    container_name: apiportal-db
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - apimarket-net

volumes:
  db-data:

networks:
  apimarket-net:
    driver: bridge
